// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: user/events/user_deleted.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeletedAt     int64                  `protobuf:"varint,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"` // Unix timestamp (seconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleted) Reset() {
	*x = UserDeleted{}
	mi := &file_user_events_user_deleted_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleted) ProtoMessage() {}

func (x *UserDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_user_events_user_deleted_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleted.ProtoReflect.Descriptor instead.
func (*UserDeleted) Descriptor() ([]byte, []int) {
	return file_user_events_user_deleted_proto_rawDescGZIP(), []int{0}
}

func (x *UserDeleted) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserDeleted) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

var File_user_events_user_deleted_proto protoreflect.FileDescriptor

const file_user_events_user_deleted_proto_rawDesc = "" +
	"\n" +
	"\x1euser/events/user_deleted.proto\x12\x06userpb\"<\n" +
	"\vUserDeleted\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x02 \x01(\x03R\tdeletedAtB\x15Z\x13proto/events/userpbb\x06proto3"

var (
	file_user_events_user_deleted_proto_rawDescOnce sync.Once
	file_user_events_user_deleted_proto_rawDescData []byte
)

func file_user_events_user_deleted_proto_rawDescGZIP() []byte {
	file_user_events_user_deleted_proto_rawDescOnce.Do(func() {
		file_user_events_user_deleted_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_events_user_deleted_proto_rawDesc), len(file_user_events_user_deleted_proto_rawDesc)))
	})
	return file_user_events_user_deleted_proto_rawDescData
}

var file_user_events_user_deleted_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_events_user_deleted_proto_goTypes = []any{
	(*UserDeleted)(nil), // 0: userpb.UserDeleted
}
var file_user_events_user_deleted_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_events_user_deleted_proto_init() }
func file_user_events_user_deleted_proto_init() {
	if File_user_events_user_deleted_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_events_user_deleted_proto_rawDesc), len(file_user_events_user_deleted_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_events_user_deleted_proto_goTypes,
		DependencyIndexes: file_user_events_user_deleted_proto_depIdxs,
		MessageInfos:      file_user_events_user_deleted_proto_msgTypes,
	}.Build()
	File_user_events_user_deleted_proto = out.File
	file_user_events_user_deleted_proto_goTypes = nil
	file_user_events_user_deleted_proto_depIdxs = nil
}
