server:
  host: "api"
  port: "8080"

database:
  host: "postgres"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "microservice_db"
  sslmode: "disable"

kafka:
  brokers:
    - "kafka:9092"
  topics:
    user_events: "user.events"

logger:
  level: "info"
